config/routes.rb
Flyloft::Application.routes.draw do
  resources :gigs

  resources :orgs

  devise_for :users do
    get 'sign_in' => 'devise/sessions#new'
    get 'sign_out' => 'devise/sessions#destroy'
    get 'sign_up' => 'devise/registrations#new'
    get 'my_account' => 'devise/registrations#edit'
  end
  
  get "users" => 'users#index'
  get "users/:id" => 'users#show', :as => :user

  
  root :to => "static#home"

end

app/models/org.rb
class Org < ActiveRecord::Base
  include Locatable

  belongs_to :contact_person, :class_name => 'User'
  has_many :gigs
  has_many :org_memberships, :dependent => :destroy
  has_many :members, :through => :org_memberships, :source => :user
  
  def to_s
    self.name
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  respond_to :html
  before_filter :authenticate_user!, :except => [:index, :show]
  
  sortable_attributes :created_at, :name, :city
  
  def index
    @orgs = Org.paginate :page => params[:page], :order => sort_order
    respond_with @orgs
  end

  def show
    @org = Org.find(params[:id])
    respond_with @org
  end

  def new
    @org = Org.new(:name => params[:name])
    @gig_id = params[:gig_id]
    respond_with @org
  end

  def edit
    @org = Org.find(params[:id])
  end

  def create
    @org = Org.new(params[:org])
    @org.contact_person ||= current_user
    
    if @org.save
      @org.members << current_user if user_signed_in?
      
      begin
        # associate with the gig
        gig = Gig.find(params[:gig][:id])
        gig.org = @org
        gig.save
      rescue
      end
      
      flash[:notice] = 'Org was successfully created.'
    end
    
    respond_with @org
  end

  def update
    @org = Org.find(params[:id])
    
    if @org.update_attributes(params[:org])
      flash[:notice] = 'Org was successfully updated.'
    end
    
    respond_with @org
  end

  def destroy
    @org = Org.find(params[:id])
    @org.destroy
    
    respond_with @org
  end
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/orgs/_form.html.haml
= form_for @org do |f|
  -if @org.errors.any?
    #error_explanation
      %h2= "#{pluralize(@org.errors.count, "error")} prohibited this org from being saved:"
      %ul
        - @org.errors.full_messages.each do |msg|
          %li= msg

  = hidden_field :gig, :id, :value => @gig_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip
    = f.text_field :zip
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :mission
    = f.text_area :mission
  .field
    = f.label :founding_year
    = f.text_field :founding_year
  .actions
    = f.submit 'Save'

app/views/orgs/edit.html.haml
%h1 Editing org

= render 'form'

= link_to 'Show', @org
\|
= link_to 'Back', orgs_path

app/views/orgs/index.html.haml
%h1 Orgs

= link_to 'Add my organization!', new_org_path

%table
  %tr
    = sortable_table_header :name => "Name",  :sort => "name"
    = sortable_table_header :name => "Location",  :sort => "city"
    = sortable_table_header :name => "Date added",  :sort => "created_at"

  - @orgs.each do |org|
    %tr
      %td= link_to org.name, org
      %td= org.location
      %td= org.created_at

%br

app/views/orgs/new.html.haml
%h1 New org

= render 'form'

= link_to 'Back', orgs_path

app/views/orgs/show.html.haml
%p
  %b Name:
  = @org.name
%p
  %b Phone:
  = @org.phone
%p
  %b Street:
  = @org.street
%p
  %b City:
  = @org.city
%p
  %b State:
  = @org.state
%p
  %b Zip:
  = @org.zip
%p
  %b Country:
  = @org.country
%p
  %b Mission:
  = @org.mission
- if @org.contact_person
  %p
    %b Contact person:
    = link_to @org.contact_person.display_name, @org.contact_person
%p
  %b Founding year:
  = @org.founding_year
%p
  %b Gigs:
  %ul
  - @org.gigs.each do |gig|
    %li
      = link_to gig.title, gig
%p
  %b Members:
  %ul
  - @org.members.each do |member|
    %li
      = link_to member.display_name, member

- if can? :edit, @org
  = link_to 'Edit', edit_org_path(@org)
  \|
- if can? :destroy, @org
  = link_to 'Destroy', @org, :confirm => 'Are you sure?', :method => :delete
  \|
= link_to 'Back', orgs_path