config/routes.rb
Flyloft::Application.routes.draw do
  resources :gigs

  resources :orgs

  devise_for :users do
    get 'sign_in' => 'devise/sessions#new'
    get 'sign_out' => 'devise/sessions#destroy'
    get 'sign_up' => 'devise/registrations#new'
    get 'my_account' => 'devise/registrations#edit'
  end
  
  get "users" => 'users#index'
  get "users/:id" => 'users#show', :as => :user

  
  root :to => "static#home"

end

app/models/gig.rb
class Gig < ActiveRecord::Base
  include Locatable
  
  default_value_for :view_count, 0
  default_value_for :post_at, DateTime.now
  default_value_for :expire_at, DateTime.now + 30.days
  default_value_for :enabled, true
  
  belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
  belongs_to :org
  has_many :auditions, :dependent => :destroy
  
  accepts_nested_attributes_for :auditions, :reject_if => :all_blank, :allow_destroy => true
  
  validates :title, :presence => true
  validate :expire_at_later_than_post_at
  validate :post_and_expire_must_be_present_to_enable
  
  
  def is_published?
    !self.new_record? and self.enabled
  end
  
  def is_draft?
    !self.new_record? and !self.enabled
  end
  
  
  private
  
  def expire_at_later_than_post_at
    if self.post_at and self.expire_at and self.post_at > self.expire_at
      errors.add(:expire_at, "must be later than the posting date")
    end
  end
  
  def post_and_expire_must_be_present_to_enable
    if self.enabled
      if self.post_at.blank?
        errors.add(:enabled, "cannot be checked unless posting date is set")
      end
      if self.enabled and self.expire_at.blank?
        errors.add(:enabled, "cannot be checked unless expiration date is set")
      end
    end
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  respond_to :html, :rss, :atom, :xml
  before_filter :authenticate_user!, :except => [:index, :show]
  
  sortable_attributes :created_at, :title, :expire_at, :city, :org => 'orgs.name'

  def index
    @gigs = Gig.paginate :page => params[:page], :order => sort_order, :include => :org
    respond_with @gigs
  end

  def show
    @gig = Gig.find params[:id], :include => [:org, :auditions, :creator]
    if !user_signed_in? or current_user != @gig.creator
      @gig.view_count += 1
      @gig.save
    end
    
    respond_with @gig
  end

  def new
    @gig = Gig.new
    @gig.auditions.build
    
    if user_signed_in?
      @gig.contact_first_name ||= current_user.first_name
      @gig.contact_last_name ||= current_user.last_name
      @gig.contact_email ||= current_user.email
    end
    
    respond_with @gig
  end

  def edit
    @gig = Gig.find(params[:id])
  end

  def create
    @gig = Gig.new(params[:gig])
    @gig.creator ||= current_user
    @gig.enabled = false if params[:commit] =~ /draft/i

    if @gig.save
      if @gig.enabled
        flash[:notice] = 'Gig was successfully listed!'
      else
        flash[:notice] = 'Gig was successfully created.'
      end
    end
    
    respond_with @gig do |format|
      if @gig.persisted? and @gig.company.present?
        format.html { redirect_to [new_org_path, "?name=#{@gig.company}&gig_id=#{@gig.id}"].join }
      end
    end
  end

  def update
    @gig = Gig.find(params[:id])
    was_enabled = @gig.enabled
    @gig.enabled = true unless params[:commit] =~ /draft/i

    if @gig.update_attributes(params[:gig])
      if !was_enabled and @gig.enabled
        flash[:notice] = 'Gig was successfully listed!'
      elsif was_enabled and !@gig.enabled
        flash[:notice] = 'Gig was successfully unlisted.'
      else
        flash[:notice] = 'Gig was successfully updated.'
      end
    end
    
    respond_with @gig
  end

  def destroy
    @gig = Gig.find(params[:id])
    @gig.destroy
    
    respond_with @gig
  end
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/_audition_fields.html.haml
= f.inputs :class => 'audition' do
  = f.inputs :place, :address, :city
  = f.input :state, :as => :select, :collection => State::NAMES
  = link_to_remove_fields "X", f
  

app/views/gigs/_form.html.haml
= semantic_form_for @gig do |f|
  -if @gig.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gig.errors.count, "error")} prohibited this gig from being saved:"
      %ul
        - @gig.errors.full_messages.each do |msg|
          %li= msg

  = f.inputs :title
  
  = f.inputs do
    - unless current_user.memberships.empty?
      = f.input :org, :include_blank => "other..."
    = f.input :company, :label => "Organization Name"

    :javascript
      function hideCompanyIfOrgSelected() {
        if ($('#gig_org_id').val() === '') {
          $('#gig_company_input').show();
        } else {
          $('#gig_company_input').hide().val('');
        }
      }
    
      $(function(){
        hideCompanyIfOrgSelected();
        $('#gig_org_id').change(function(e){ hideCompanyIfOrgSelected(); });
      });
  
  = f.inputs :name => "Location" do
    = f.input :city
    = f.input :state, :as => :select, :collection => State::NAMES
      
  = f.inputs :name => "Contact Info" do
    = f.input :contact_first_name, :label => "First Name"
    = f.input :contact_last_name, :label => "Last Name"
    = f.input :contact_email, :label => "Email"
  
  = f.inputs :name => "Auditions" do
    = f.semantic_fields_for :auditions do |audition_form|
      = render :partial => 'gigs/audition_fields', :locals => {:f => audition_form}
    = link_to_add_fields "Add Audition", f, :auditions
  
  = f.inputs do
    = f.input :post_at, :label => "Post on", :as => :date_picker
    = f.input :expire_at, :label => "Expire on", :as => :date_picker

  :javascript
    $(function(){
      var dates = $( "#gig_post_at, #gig_expire_at" ).datepicker({
        onSelect: function( selectedDate ) {
          var option = this.id == "gig_post_at" ? "minDate" : "maxDate",
            instance = $( this ).data( "datepicker" );
          date = $.datepicker.parseDate(
            instance.settings.dateFormat ||
            $.datepicker._defaults.dateFormat,
            selectedDate, instance.settings
          );
          dates.not( this ).datepicker( "option", option, date );
        }
      });
    });
  
  = f.inputs :description
  
  = f.buttons do
    - if @gig.new_record?
      = f.commit_button "Post it!"
    - else
      = f.commit_button "Update"
    = f.commit_button "Save Draft" unless @gig.is_published?

app/views/gigs/edit.html.haml
%h1 Editing gig

= render 'form'

= link_to 'Show', @gig
\|
= link_to 'Back', gigs_path

app/views/gigs/index.html.haml
- content_for :additional_head_info do
  = auto_discovery_link_tag

%h1 Gigs

= link_to 'Add a gig!', new_gig_path

%table
  %tr
    = sortable_table_header :name => "Title",  :sort => "title"
    = sortable_table_header :name => "Org",  :sort => "org"
    = sortable_table_header :name => "Location",  :sort => "city"
    = sortable_table_header :name => "Posted",  :sort => "created_at"
    = sortable_table_header :name => "Expires",  :sort => "expire_at"

  - @gigs.each do |gig|
    %tr
      %td= link_to gig.title, gig
      %td= link_to_org(gig)
      %td= gig.location
      %td= gig.post_at
      %td= gig.expire_at

%br

app/views/gigs/index.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
	<title>RSS Title</title>
	<description>This is an example of an RSS feed</description>
	<link><%= request.url %></link>
	<atom:link href="<%= request.url  %>" rel="self" type="application/rss+xml" />
	<lastBuildDate><%= DateTime.now.rfc822 %></lastBuildDate>
	<pubDate><%= DateTime.now.rfc822 %></pubDate>
  
  <% @gigs.each do |gig| %>
	<item>
		<title><%= gig.title %></title>
		<description><%= gig.description %></description>
		<link><%= request.protocol %><%= request.host_with_port %><%= gig_path gig %></link>
		<guid><%= request.protocol %><%= request.host_with_port %><%= gig_path gig %></guid>
		<pubDate><%= gig.post_at.rfc822 %></pubDate>
	</item>
	<% end %>

</channel>
</rss>

app/views/gigs/new.html.haml
%h1 New gig

= render 'form'

= link_to 'Back', gigs_path

app/views/gigs/show.html.haml
%h1
  = @gig.title
%div
  .org_name
    = link_to_org(@gig)
  .location
    = @gig.location
%div
  %h2 Description
  %p
    = @gig.description
%div
  %h2 Auditions
  %ul
    - @gig.auditions.each do |audition|
      %li.audition
        = audition.place
        %br
        = audition.location
        - if audition.start_at
          %br
          = audition.start_at.to_s :date
          %br
          = audition.start_at.to_s :time
          - if audition.end_at
            \-
            = audition.end_at.to_s :time
%div
  %h2 Contact Info
  = @gig.contact_first_name
  = @gig.contact_last_name
  %br
  = mail_to @gig.contact_email
%div
  %p
    %b Posted:
    = @gig.post_at
  %p
    %b Expires:
    = @gig.expire_at
  %p
    %b View count:
    = @gig.view_count

- if can? :edit, @gig
  = link_to 'Edit', edit_gig_path(@gig)
  \|
- if can? :destroy, @gig
  = link_to 'Destroy', @gig, :confirm => 'Are you sure?', :method => :delete
  \|
= link_to 'Back', gigs_path