config/routes.rb
Flyloft::Application.routes.draw do
  resources :gigs

  resources :orgs

  devise_for :users do
    get 'sign_in' => 'devise/sessions#new'
    get 'sign_out' => 'devise/sessions#destroy'
    get 'sign_up' => 'devise/registrations#new'
    get 'my_account' => 'devise/registrations#edit'
  end
  
  get "users" => 'users#index'
  get "users/:id" => 'users#show', :as => :user

  
  root :to => "static#home"

end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Flyspace
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Flyloft
    = stylesheet_link_tag 'scaffold'
    = stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.6.custom.css'
    = stylesheet_link_tag 'formtastic'
    = stylesheet_link_tag 'screen'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js'
    = javascript_include_tag 'jquery-ui-1.8.5.datepicker.min'
    = javascript_include_tag 'rails'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = yield :additional_head_info
  %body
    #wrapper
      #header
        #banner
          = link_to "Flyloft", root_path
        #account
          - if user_signed_in?
            #{current_user.first_name} #{current_user.last_name.first}.
            = link_to "My Account", my_account_path
            = link_to "Sign out", sign_out_path
          - else
            = link_to "Sign up", sign_up_path
            or
            = link_to "sign in", sign_in_path
        .clear
      #nav-bar
        = render_navigation
        .clear
      - if notice
        #notice
          = notice
      - if alert
        #alert
          = alert
      #contents
        = yield